
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Nav from "../ui/Nav";
import { HeroPage } from "../ui/HeroPage";
import Footer from "../ui/utilComp/Footer";
import { SessionProvider } from "next-auth/react";
import Tab3 from "../ui/Tab3";







const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Discover Exciting Post",
  description: "Generated by create next app",
};

export default async function homeLayout({children}) {
 
  
//   if(session?.user){
//     session.user = {
//       name : session.user.name,
//       email: session.user.email,
//       image: session.user.image
//     }
//   }
  
  return (
   
    
      <SessionProvider baseUrl={"/api/auth"}>
      <div className="w-screen space-y-20 pb-20">
      <header className=" fixed  top-0 z-50 w-screen py-4 bg-indigo-600 ">
     <span className="">
     <h1 className="text-center text-white font-semibold text-lg">Discover </h1>
     </span>
    
      
      
      </header>
      
     
      
    
      <main className="grid grid-cols-1 gap-0 md:grid-cols-2 md:gap-2 lg:grid-cols-1  lg:gap-2 lg:px-14  mx-auto p-4">
      {children}
     
     
      </main>
      
      </div>
      </SessionProvider>
      
    
  );
}
