
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { SessionProvider } from "next-auth/react";






const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Products",
  description: "Generated by create next app",
};

export default async function StoreLayout({children}) {
 
  
  
  return (
   <>
  {children}
   </>
    
      
    
  );
}
