import { Inter } from "next/font/google";
import "@/app/globals.css";
import Nav from "../ui/Nav";
import { HeroPage } from "../ui/HeroPage";
import Footer from "../ui/utilComp/Footer";
import { SessionProvider } from "next-auth/react";
import Tab3 from "../ui/Tab3";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Welcome To Mymart",
  description: "Generated by create next app",
};

export default async function homeLayout({ children, tab, arrivals, ...rest }) {
  //   if(session?.user){
  //     session.user = {
  //       name : session.user.name,
  //       email: session.user.email,
  //       image: session.user.image
  //     }
  //   }

  return (
    <SessionProvider baseUrl={"/api/auth"}>
      <Nav />

      <HeroPage />

      {/* <main className="grid grid-cols-1 gap-2 md:grid-cols-2 md:gap-2 lg:grid-cols-1  lg:gap-2 lg:px-14  mx-auto px-4"> */}
        <section className="pb-1 pt-4 space-y-1 px-4">
          {tab}

          {arrivals}
        </section>

       
        {/* </main> */}
        <section className="px-4">
        <Tab3 data={null} />
        {children}
        </section>

      <Footer />
    </SessionProvider>
  );
}
