
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Nav from "@/app/ui/Nav";
import ButtomNav from "@/app/ui/buttomNav";
import StoreProvider from "@/app/StoreProvider";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  //const pathname = await getRoute()
  return (
    <html lang="en">
      <StoreProvider>
      <body className={`${inter.className} min-h-screen w-full overflow-x-clip `}>
      
      <header className="bg-indigo-700">
      
      <Nav/>
      
      </header>
      <main>
      {children}
      </main>
      <footer className="bg-[#4f08ed] w-full">
        
          <ButtomNav/>
        
      </footer>
      </body>
      </StoreProvider>
    </html>
  );
}
