import { Inter } from "next/font/google";
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default async function homeLayout({ children }) {
  return <main className="min-h-screen bg-white">{children}</main>;
}
