
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { SessionProvider } from "next-auth/react";
import Header from "@/app/ui/utilComp/Header";
import {Divider} from '@mui/material'





const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "create a Store",
  description: "Generated by create next app",
};

export default async function StoreLayout({children, recommended, branch, products, ...rest}) {
 
  const id = rest?.params.id,
   visi = false;
  
  return (
   
    <>
      <SessionProvider baseUrl={"/api/auth"}>
      <header className="mx-auto" >
      <Header params = {id}/>
      </header>
        
      <main className="grid grid-cols-1 gap-6 mt-[9.1rem]  text-sm">

      {/* <main className="flex flex-col m-4 space-y-14 mb-10 container  mt-40 md:flex text-black lg:flex md: justify-around"> */}
      <section className=" bg-slate-50 text-gray-900 mt-4 space-y-4">
      {children}
      </section>
      <section>
      {branch}
      </section>
      <section>
      {products}
      </section>
      <section>
      {recommended}
      </section>
      </main>
      </SessionProvider>
      </>
    
  );
}
