import { Inter } from "next/font/google";
import "@/app/globals.css";
import { SessionProvider } from "next-auth/react";
import "react-toastify/dist/ReactToastify.css";
import { redirect } from "next/navigation";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Dashboard",
  description: "Generated by create next app",
};

export default async function StoreLayout({ children }) {
  const session = await auth();

  if (!session) {
    redirect("/login");
  }
  return (
    <>
      <SessionProvider baseUrl={"/api/auth"}>{children}</SessionProvider>
    </>
  );
}
