
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { SessionProvider } from "next-auth/react";
import Header from "@/app/ui/utilComp/Header";
import 'react-toastify/dist/ReactToastify.css';
import { headers } from "next/headers";
import dynamic from "next/dynamic";

// const { toast, ToastContainer} = dynamic(()=> import(`react-toastify`), {ssr: false})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "create a Store",
  description: "Generated by create next app",
};

export default async function StoreLayout({children, recommended, branch, products, ...rest}) {
  const header = headers()
  const domain = header.get("host");
  console.log(rest)
  const response =  await fetch(
    `http://${domain}/api/store/${rest?.params.storeOwner}/${rest?.params.id}/`,
    
    )
   
  
  const users = await response.json()
  if(users?.message){
   
  }
  return (
   
    <>
      <SessionProvider baseUrl={"/api/auth"}>
  
      <div className="flex flex-col space-y-24 lg:space-y-14  md:space-y-14  w-screen  bg-['#f0e4f9']">
      
      <header className="mx-auto bg-white z-50" >
      <Header params = {6} message = {users.message}/>
      </header>
     
      <main id='tray' className="  flex flex-col space-y-1 text-sm md:text-base  lg:text-balance lg:text-base">
      
      {/* <main className="flex flex-col m-4 space-y-14 mb-10 container  mt-40 md:flex text-black lg:flex md: justify-around"> */}
      <section id='focal' className="w-screen fixed invisible h-10 mb-24"></section>
      <section id='abouts' className=" bg-white">
      <section  className=" bg-white  text-gray-800 p-4 w-screen md:w-auto ">
      {children}
      </section>
      <hr className="h-4"/>
      <section className="bg-white w-screen lg:w-auto p-4 md:w-auto md:text-wrap">
      {branch}
      </section>
      </section>
      <section id='product' className="p-2 bg-white text-gray-900 lg:p-12 lg:w-screen">
      {products}
      </section>
      <section id = 'reco' className="bg-white">
      {recommended}
      </section>
      </main>
      </div>
      </SessionProvider>
      </>
    
  );
}
