
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { SessionProvider } from "next-auth/react";
import Header from "@/app/ui/utilComp/Header";
import { headers } from "next/headers";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "create a Store",
  description: "Generated by create next app",
};

export default async function StoreLayout({children, recommended, branch, products, ...rest}) {
  const header = headers()
  const domain = header.get("host");
  const response =  await fetch(
    `http://${domain}/api/store/${rest?.params.storeOwner}/${rest?.params.id}/`
    
    )
   
  
  const users = await response.json()
  console.log(users)
  return (
   
    <>
      <SessionProvider baseUrl={"/api/auth"}>
  
      <div className="flex flex-col space-y-40 lg:space-y-40  md:space-y-40  w-screen overflow-x-clip pb-16">
      
    
      <Header params = {6} message = {users.message} storeInfo = {users?.data || {}}/>
      
     
      <main id='tray' className="  flex flex-col space-y-1 text-sm md:text-base  lg:text-balance lg:text-base">
      
      {/* <main className="flex flex-col m-4 space-y-14 mb-10 container  mt-40 md:flex text-black lg:flex md: justify-around"> */}
      <section id='focal' className="w-screen fixed bg-pink-700 invisible h-10 mb-24"></section>
      <section id='abouts' className=" bg-white p-4 space-y-2 ">
      <section  className=" bg-white  text-gray-800 md:w-auto pb-2 px-2">
      {children}
      </section>
      {/* <hr className="h-4"/> */}
      <section className="bg-white  lg:w-auto md:w-auto md:text-wrap p-2 px-2">
      {branch}
      </section>
      </section>
      {/* <hr className="h-4"/> */}
      <section id='product' className="  px-6  bg-white text-gray-900 lg:p-12 lg:w-screen">
      {products}
      </section>
      <section id = 'reco' className="bg-white">
      {/* {recommended} */}
      </section>
      </main>
      </div>
      </SessionProvider>
      </>
    
  );
}
