
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { SessionProvider } from "next-auth/react";






const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "create a Store",
  description: "Generated by create next app",
};

export default async function StoreLayout({children, store, branch, ...rest}) {
 
  console.log(children)
  
  return (
   
    <>
      <SessionProvider baseUrl={"/api/auth"}>
      <main className="">
      <section className=" bg-slate-50 text-black flex flex-col space-y-1 w-[100vw]">
      {store}
      </section>
      <section className=" bg-slate-50 text-black flex flex-col space-y-1 w-[100vw]">
      {branch}
      </section> 
      </main>
      </SessionProvider>
      </>
    
  );
}
